### PR TITLE
BUG: errR undefined in certain cases

### LINKED ISSUE #38: dada2 denoise-paired-end run failed with default `n-reads-learn` (i.e., 1,000,000), but not with `n-reads-learn=10000`
It ran for about an hour, and then failed with the following traceback:

```
$ qiime dada2 denoise-paired --i-demultiplexed-seqs ../demux-paired.qza --p-trunc-len-f 100 --p-trunc-len-r 100 --p-trim-left-f 0 --p-trim-left-r 0 --o-table table-default --o-representative-sequences rep-set-default --p-n-threads 0 --verbose
object 'errR' not found
Execution halted
Traceback (most recent call last):
  File "/home/gregcaporaso/.conda/envs/qiime2-dev/bin/qiime", line 11, in <module>
    load_entry_point('q2cli==2017.2.0.dev0', 'console_scripts', 'qiime')()
  File "/home/gregcaporaso/.conda/envs/qiime2-dev/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/gregcaporaso/.conda/envs/qiime2-dev/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/gregcaporaso/.conda/envs/qiime2-dev/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gregcaporaso/.conda/envs/qiime2-dev/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gregcaporaso/.conda/envs/qiime2-dev/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gregcaporaso/.conda/envs/qiime2-dev/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/gregcaporaso/.conda/envs/qiime2-dev/lib/python3.5/site-packages/q2cli/commands.py", line 215, in __call__
    results = action(**arguments)
  File "<decorator-gen-191>", line 2, in denoise_paired
  File "/home/gregcaporaso/.conda/envs/qiime2-dev/lib/python3.5/site-packages/qiime2/sdk/action.py", line 171, in callable_wrapper
    output_types, provenance)
  File "/home/gregcaporaso/.conda/envs/qiime2-dev/lib/python3.5/site-packages/qiime2/sdk/action.py", line 248, in _callable_executor_
    output_views = callable(**view_args)
  File "/home/gregcaporaso/.conda/envs/qiime2-dev/lib/python3.5/site-packages/q2_dada2/_denoise.py", line 98, in denoise_paired
    return _denoise_helper(cmd, biom_fp, hashed_feature_ids)
  File "/home/gregcaporaso/.conda/envs/qiime2-dev/lib/python3.5/site-packages/q2_dada2/_denoise.py", line 34, in _denoise_helper
    run_commands([cmd])
  File "/home/gregcaporaso/.conda/envs/qiime2-dev/lib/python3.5/site-packages/q2_dada2/_plot.py", line 26, in run_commands
    subprocess.run(cmd, check=True)
  File "/home/gregcaporaso/.conda/envs/qiime2-dev/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['run_dada_paired.R', '/tmp/tmp3u_qh3d4/forward', '/tmp/tmp3u_qh3d4/reverse', '/tmp/tmp3u_qh3d4/output.tsv.biom', '/tmp/tmp3u_qh3d4/filt_f', '/tmp/tmp3u_qh3d4/filt_r', '100', '100', '0', '0', '2.0', '2', '0', '1000000']' returned non-zero exit status 1
```

This looks like it's coming from the R code based on this error:

```
object 'errR' not found
```

Weirdly, this command completed successfully:

```
$ qiime dada2 denoise-paired --i-demultiplexed-seqs ../demux-paired.qza --p-trunc-len-f 100 --p-trunc-len-r 100 --p-trim-left-f 0 --p-trim-left-r 0 --o-table table --o-representative-sequences rep-set --p-n-threads 0 --p-n-reads-learn 10000
Saved FeatureTable[Frequency] to: table.qza
Saved FeatureData[Sequence] to: rep-set.qza
```

### PR DESCRIPTION
**Pull request by ebolyen**
fixes #38 (maybe??)

I can't say I understand what this is doing, but it looks like the culprit for why `errR` would be undefined sometimes. @gregcaporaso would you be able to test to see if it works?

### CODE REVIEW

File: q2_dada2/assets/run_dada_paired.R [hunk 1]
```diff
@@ -190,6 +190,7 @@ if(i==1) {
   errR <- ddsR$err_out
 } else {
   errF <- ddsF[[1]]$err_out
+  errR <- ddsR[[1]]$err_out
```
Comment (ebolyen) [inline q2_dada2/assets/run_dada_paired.R]: This is the only actual change (other than the terminal whitespace).

Comment (benjjneb) [inline q2_dada2/assets/run_dada_paired.R]: Good catch.
